version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=r00t
            - MYSQL_DATABASE=clix2brix
            - MYSQL_USER=clix
            - MYSQL_PASSWORD=2br1x
        networks:
            - clix2brix
    web:
        build: .
        image: templaravel
        environment:
            - APP_KEY=t24KifsfAH3jmXRwzI91PfTzSfixd6QU
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=clix2brix
            - DB_USERNAME=clix
            - DB_PASSWORD=2br1x
        ports:
            - "80:80"
        networks:
            - clix2brix

networks:
    clix2brix:
